### ISSUE TITLE
Source des données ?

### ISSUE THREAD

**Issue by briatte** [Tutuchan/gilets-jaunes#2]
Bonjour,

Les données proviennent-elles de [blocage17novembre.com](https://www.blocage17novembre.com/carte-interactive-officielle) ?

**Comment by Tutuchan** [comment]
Bonjour,

Apparemment oui, j'avais mis le lien vers cette carte directement: https://www.google.com/maps/d/u/0/viewer?mid=1KpiLiS657xM-oR5eBHFSvP9lQM2Eyruh&ll=18.49050915137178%2C24.822041549999994&z=3 je ne savais pas qu'il existait un site.

Je peux rajouter la mention si vous le désirez.

**Comment by briatte** [comment]
Merci pour votre réponse. Oui, cela serait utile, non ?

**Comment by Tutuchan** [comment]
J'ai ajouté la mention dans le README, je vais mettre à jour le code maintenant.

Merci d'avoir relevé ce point !
